spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: performance-test-group
      auto-offset-reset: latest
    producer:
      acks: all
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG